site_name: MkLorum
site_url: https://secops.com/

nav:
    - Home: index.md
    - About: about.md

theme:
  name: null
  custom_dir: 'mkdocs-docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html


# add theme version number here
extra:
    version: 0.3.x