site_name: MkLorum
site_url: https://secops.com/

nav:
    - Home: index.md
    - About: about.md

theme:
  name: null
  custom_dir: 'cinder'


# add theme version number here
extra:
    version: 0.3.x